### PR TITLE
remove node-crc from deps in hw-app-str

### LINKED ISSUE #154: hw-app-str doesn't work with angular 6
angular 6 removed from webpack configuration nodejs core modules shims.. see https://github.com/stellar/js-stellar-base/issues/128 and https://github.com/angular/devkit/issues/967#issuecomment-391385515

i managed how to make stellar sdk work including the compiled version instead of the sources.

now my app fails with `hw-app-str` package because the code is depending on webpack that is not importing nodejs core modules shims:

image

### PR DESCRIPTION
**Pull request by phra**
fixes #154

### CODE REVIEW

**Comment by phra** [comment]
is the CI broken? it doesn't seem to be related to these changes. 

image

**Comment by gre** [comment]
probably yeah. i'll take a look asap

**Comment by phra** [comment]
@gre thanks!

**Comment by phra** [comment]
@gre done! i've also committed `yarn.lock` since i've updated `package.json` in the PR.

**Pull request merged**
