### PR TITLE
Introduce devices and refactoring of transports

### PR DESCRIPTION
**Pull request by gre**
- introduces @ledgerhq/devices package to deal with different devices and share some information.
- #281 close() now waits that the exchange() has finished in the returned promise
- #280 there is a `deviceModel` field in the event of `listen()`
- React Native Bluetooth: fixes "Operation was cancelled" bug in Samsung S9
- #279 web-ble implementation implements a workaround for a bug in current NanoX firmware
- full refactoring of node-hid implementation from the work done in webusb implementation. Much simpler code and more robust. Also using the HID channels.
- factorization of the "atomic" logic used in many hw-transport implementations.
- web-ble implementation loads the MTU at open() to benefit of better performance.
- #69 node-hid transport implementation emits a "disconnect" event when a write/read throw a "cannot write" or "cannot read" error.
- `packages/documentation-website/` is removed because not maintained. we'll rewrite proper documentation soon.

... more to detail...

...to be continued...

## Deprecated

- `TransportError` and `TransportStatusError` should be imported from `@ledgerhq/errors`

## Breaking changes

none

## Repository changes

- complete rewrite of the README.md
- examples are moving to https://github.com/LedgerHQ/ledgerjs-examples
- documentation project is removed, we'll write better documentation in each package README

---

## Remaining to do

- heavily test ledger-live-desktop with it.
- heavily test ledger-live-mobile with it.

## Later

- share more code of BLE framing implementation
- TransportError: might replace it entirely with better precision error. maybe only keep it for protocol errors.
- @ledgerhq/react-native-hid => @ledgerhq/hw-transport-react-native-hid ?
- @ledgerhq/react-native-hw-transport-ble => @ledgerhq/hw-transport-react-native-ble ?

### CODE REVIEW

**Comment by gre** [comment]
@meriadec i've updated node-hid in this PR and it seems to fail the CI now, do you have any clue what we can try? (NB, in this PR i'm switching over circleci which worked fine until this bump!)

**Comment by gre** [comment]
`4.37.0-beta.2b8718d2`

**Comment by meriadec** [comment]
Looks related to missing libudev (it was installed by the Travis config file). Can you try adding it in the install step of Circle config?

**Comment by meriadec** [comment]
Sorry I meant libusb

**Comment by gre** [comment]
fixed. thx

**Pull request merged**
