### PR TITLE
Fixes README typos

### PR DESCRIPTION
**Pull request by jritchie-nullable**
- fixes references to Algorand
- fixes typo
- updates BIP 32 path

### CODE REVIEW

**Comment by jritchie-nullable** [comment]
https://github.com/LedgerHQ/ledgerjs/issues/781

**Review by ghost — APPROVED** [review]
Thanks !

**Review by ghost — CHANGES_REQUESTED** [review]
CI failure, need to figure it out...
@gre if you have an idea?

**Comment by gre** [comment]
the doc is generated from the code, the typo are in comment of the code.

**Comment by gre** [comment]
if you run `yarn doc` it will regenerate it.  but the root issue is at https://github.com/LedgerHQ/ledgerjs/blob/d3736e136b55100ec3c6464253224eb8013fd34a/packages/hw-app-algorand/src/Algorand.ts#L35

**Comment by gre** [comment]
I'll take it

**Pull request closed without merging**
