### PR TITLE
feat(hw-app-str): generalize for more networks

### PR DESCRIPTION
**Pull request by Akuukis**
At [ledger-app-stellar #11](https://github.com/lenondupe/ledger-app-stellar/issues/11) it was clear that each Stellar technology based network will have to make it's own app. Nevertheless, I see that with this change it's easy to use the same companion Javascript library for all of them.

Tested and works for me with [FIC Network](https://github.com/ficnetwork/ledger-app-fic).

Is this the right way to move forward?

### CODE REVIEW

**Comment by Akuukis** [comment]
Updated the PR to latest master. Stellar contributors @lenondupe @phra , what are your thoughts on this?

**Comment by lenondupe** [comment]
I'd prefer to simply remove the check altogether to be honest. If there is there a dedicated status word that is returned for when a request is made that does not correspond to the lock path of the app we may catch it and make a more descriptive message for the caller about what's going but otherwise I'd simply just remove the check.

**Comment by Akuukis** [comment]
@lenondupe Ok, makes sense. I've done so, can you please review?

Maintainers, I am confused why Travis is failing, and why it's out-of-date. Travis doesn't have any errors, nor I see any new changes in master.

**Comment by Akuukis** [comment]
@lenondupe bump.

**Comment by lenondupe** [comment]
Sorry, yeah, looks good to me. @gre can this be merged?

**Pull request merged**
