### PR TITLE
20220309 CAL update

### PR DESCRIPTION
**Pull request by adrienlacombe**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM but I don't know what to check.
@gre Is there anything specific to check this kind of update, and when should we merge them?

**Comment by adrienlacombe-ledger** [comment]
I think you would need to do a "release" of the cryptoassets package, if that makes sense and then include this new version everywhere. I let @gre confirm. Tahn kyou :pray:

**Comment by gre** [comment]
ledgerjs crypto list = if it pass the ci it's good to merge.

now for the Ledger Live side: the ledgerjs package just was released a day ago with previous iteration, so i guess this will need to go in the next future train we have on this stack

**Comment by adrienlacombe-ledger** [comment]
yes np, thank you @gre :)

**Pull request merged**
