### PR TITLE
Peercoin v11 and new explorer

### PR DESCRIPTION
**Pull request by backpacker69**
related to https://github.com/LedgerHQ/ledgerjs/issues/701

### CODE REVIEW

**Comment by gre** [comment]
So if i'm correct this fix will only work with the same fix done on the nano app at https://github.com/LedgerHQ/app-bitcoin/pull/210 , correct?

**Comment by backpacker69** [comment]
this fix will work alone insofar that ledgerjs library will be able to split new peercoin transactions properly without crashing in the middle, but fix LedgerHQ/app-bitcoin#210 is also necessary for end users of ledger live to be able to sign v3+ peercoin transactions and actually be capable of spending peercoins from v3+ inputs.

what i couldn't find is where additionals are populated in ledger live, so this line would work and set this variable properly.

`const isPeercoin = additionals.includes("peercoin");
`

**Comment by FabriceDautriat** [comment]
Linked to : https://github.com/LedgerHQ/app-bitcoin-new/pull/10
@tjulien-ledger

**Review by gre — CHANGES_REQUESTED** [review]
instead of introducing one more flag, we are considering having less intelligence in ledgerjs but more on user land, which means , instead of the suggested changes, we prefer to let the user land set `hasTimestamp` to false when it satisfy the blockchain(s).

we have ongoing test that confirm this approach works https://github.com/LedgerHQ/ledger-live-common/pull/1621/files

as for the explorersViews change, feel free to send a dedicated PR for it but it's better to split the two topics. thanks

**Comment by backpacker69** [comment]
> https://github.com/LedgerHQ/ledger-live-common/pull/1621/files

problem with this approach is that it cannot handle inputs in older version transactions, which means that you won't be able to spend old coins in your wallet for example. I cannot figure out how to control this from user land, set hasTimestamp to false before calling to split  but how to call sign transaction with both types?

**Comment by hzheng-ledger** [comment]
@backpacker69 
good point.
I think I should do this:
`        if (version !== "01000000" && version !== "02000000") {
          hasTimestamp = false;
        }
        else{
          hasTimestamp = true;
        }

`
So, "hasTimestamp = true" for inputs in older version, "hasTimestamp = false" for inputs in new version.
Do I understand correctly?

**Comment by backpacker69** [comment]
I think that if hasTimestamp parameter can be reconfigured according to transaction version, then it should work.

**Comment by hzheng-ledger** [comment]
Yes, I agree.
Also, I see that you suggest to change the peercoin explorer url from "https://explorer.peercoin.net" to "https://blockbook.peercoin.net"
Are they different?

**Comment by peerchemist** [comment]
> Yes, I agree. Also, I see that you suggest to change the peercoin explorer url from "https://explorer.peercoin.net" to "https://blockbook.peercoin.net" Are they different?

Both lead to the same service, but we are trying to migrate to only "blockbook.peercoin.net" domain.

**Comment by gre** [comment]
My understand is we managed to fix it on the "user land" side so the logic can happen outside of the library and this fix is no longer needed. Don't hesitate to comment if i'm wrong. Thanks.

**Pull request closed without merging**
