### PR TITLE
Add AlgoGems, Yieldly, Smile Coin & Opulous

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by haammar-ledger** [comment]
Hi @salvatorecorvaglia, if I'm not mistaken the ASA list defined here has to match the one that's hardcoded in the Nano app i.e https://github.com/LedgerHQ/app-algorand/blob/fab72c70352c9405cd8cb46e579fb907f71d9b3e/src/algo_asa.c#L15-L37
I believe the list in the Nano app should be updated first, right?

**Comment by salvatorecorvaglia** [comment]
Yes, in fact I sent a Pull Request with the changes to be made there too:
https://github.com/algorand/ledger-app-algorand/pull/56

**Comment by haammar-ledger** [comment]
> Yes @haammar-ledger, in fact I sent a Pull Request with the changes to be made there too: [algorand/ledger-app-algorand#56](https://github.com/algorand/ledger-app-algorand/pull/56)

Indeed, my bad I missed that. Thanks.

**Comment by FabriceDautriat** [comment]
Hello @salvatorecorvaglia ,

The Algorand team is in charge of adding new ASAs. I suggest you to get in touch with them so they can make the corresponding PRs.

You can reach them on our [Discord](https://discord.gg/Ledger).

I'll also update the documentation to reflect that new ASA request must go through the Algorand team first.
https://developers.ledger.com/docs/token/asa/

Long term, we'll find a better solution.

Regards,

**Comment by salvatorecorvaglia** [comment]
Perfect @FabriceDautriat, thanks.

**Pull request closed without merging**
