### PR TITLE
Fix XST: set default versino to v2 for XST not to have timestamp

### PR DESCRIPTION
**Pull request by KhalilBellakrid**
Related to : https://ledgerhq.atlassian.net/browse/LLC-214

### CODE REVIEW

**Comment by gre** [comment]
@KhalilBellakrid can you `yarn prettier` ? Thx

**Comment by KhalilBellakrid** [comment]
Done, btw weird that those file were changed, no ? 🤔

**Comment by gre** [comment]
Mmh something is weird, I'll check on my side.
You confirm you don't have prettier installed globally? Normally it's installed by the ledgerjs as a devdep

**Comment by gre** [comment]
i've directly cherry-picked from master. this was the `yarn prettier` result on my side, https://github.com/LedgerHQ/ledgerjs/commit/44e95ae9f5b0a954b2bdebea68eaa03a24e289eb

i recommend to uninstall the global install of prettier that must be outdated

**Pull request closed without merging**
